/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DayDescriptionDto { 
    id?: number;
    description?: string;
    imageUrl?: string;
    programmedEventId?: number;
}

