/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Event } from './event';


export interface DayDescription { 
    id?: number;
    description?: string;
    imageUrl?: string;
    eventId?: number;
    event?: Event;
}

