/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventResponse } from './eventResponse';


export interface DayDescriptionResponse { 
    id?: number;
    description?: string;
    imageUrl?: string;
    eventId?: number;
    event?: EventResponse;
}

