/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentImported { 
    id?: string;
    fileName?: string;
    mimeType?: string;
    objectKey?: string;
    bucket?: string;
}

