/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizerResponse } from './organizerResponse';


export interface EventResponse { 
    id?: number;
    initDate?: string;
    organizerId?: number;
    signs?: number;
    eventId?: number;
    locationId?: number;
    organizer?: OrganizerResponse;
}

