/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Event } from './event';


export interface EventDescription { 
    id?: number;
    eventId?: number;
    objectivesText?: string;
    eventName?: string;
    eventDescription?: string;
    event?: Event;
    imageUrl?: string;
}

