/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventDescriptionDto { 
    id?: number;
    imageUrl?: string;
    programmedEventId?: number;
    objectivesText?: string;
    eventName?: string;
    locationSrc?: string;
    eventDescription?: string;
}

