/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Organizer } from './organizer';
import { EventDescription } from './eventDescription';
import { Location } from './location';


export interface Event { 
    id?: number;
    initDate?: string;
    endDate?: string;
    organizerId?: number;
    locationId?: number;
    eventTypeId?: number;
    signs?: number;
    organizer?: Organizer;
    location?: Location;
    eventDescription?: EventDescription;
}

