/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventDescriptionUrlResponse } from './eventDescriptionUrlResponse';
import { Organizer } from './organizer';
import { EventCategoryResponse } from './eventCategoryResponse';
import { Location } from './location';


export interface EventCompleteResponse { 
    initDate?: string;
    organizer?: Organizer;
    signs?: number;
    eventId?: number;
    locationId?: number;
    eventDescription?: EventDescriptionUrlResponse;
    location?: Location;
    categories?: Array<EventCategoryResponse>;
}

