/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Organizer } from './organizer';


export interface EventOrganizerResponse { 
    id?: number;
    initDate?: string;
    organizer?: Organizer;
    signs?: number;
    eventId?: number;
    locationId?: number;
}

