/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LocationResponse { 
    id?: number;
    name?: string;
    latitude?: number;
    longitude?: number;
    cityId?: number;
    addressLabel?: string;
}

