/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Organizer { 
    id?: number;
    nif?: string;
    name?: string;
    last_names?: string;
    email?: string;
    phone?: number;
    location_id?: number;
    resp_name?: string;
    resp_nif?: string;
    resp_phone?: number;
}

