/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizerDto } from './organizerDto';


export interface ProgrammedEventOrganizerDto { 
    id?: number;
    dateTime?: string;
    signs?: number;
    eventId?: number;
    locationId?: number;
    organizer?: OrganizerDto;
}

