export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './cityController.service';
import { CityControllerService } from './cityController.service';
export * from './countryController.service';
import { CountryControllerService } from './countryController.service';
export * from './documentController.service';
import { DocumentControllerService } from './documentController.service';
export * from './eventCategoryController.service';
import { EventCategoryControllerService } from './eventCategoryController.service';
export * from './eventController.service';
import { EventControllerService } from './eventController.service';
export * from './eventDescriptionController.service';
import { EventDescriptionControllerService } from './eventDescriptionController.service';
export * from './eventDescriptionImageController.service';
import { EventDescriptionImageControllerService } from './eventDescriptionImageController.service';
export * from './eventTypeController.service';
import { EventTypeControllerService } from './eventTypeController.service';
export * from './imageTypeController.service';
import { ImageTypeControllerService } from './imageTypeController.service';
export * from './locationController.service';
import { LocationControllerService } from './locationController.service';
export * from './organizerController.service';
import { OrganizerControllerService } from './organizerController.service';
export * from './signerController.service';
import { SignerControllerService } from './signerController.service';
export * from './stateController.service';
import { StateControllerService } from './stateController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AuthControllerService, CityControllerService, CountryControllerService, DocumentControllerService, EventCategoryControllerService, EventControllerService, EventDescriptionControllerService, EventDescriptionImageControllerService, EventTypeControllerService, ImageTypeControllerService, LocationControllerService, OrganizerControllerService, SignerControllerService, StateControllerService, UserControllerService];
